include "application.conf"

db.default.driver = "com.mysql.cj.jdbc.Driver"
db.default.url = "jdbc:mysql://mysql:3306/influuntdev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
db.default.username = "influunt"
db.default.password = "influunt"

play.evolutions.db.default.autoApply = true
play.evolutions.db.default.autoApplyDowns = true

playjongo.uri = "mongodb://mongo:27017/influuntdev"
playjongo.test-uri = "mongodb://mongo:27017/influunttest"

play.mailer.host = "mailhog"
play.mailer.port = 1025

influuntUrl = "http://localhost:8080"
influuntUrl = ${?INFLUUNT_URL}

central.baseUrl = "http://127.0.0.1:9000/central/v1"
central.mqtt.host = "mosquitto"
central.mqtt.port = 1883
central.mqtt.login = ""
central.mqtt.senha = ""
